<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[8]=array(0,1,1,'5pyN5Yqh5LuL57uN');
$cfg_Cs[7]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[4]=array(0,1,1,'5bel5L2c6aG555uu');
$cfg_Cs[6]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[9]=array(0,1,1,'5LqS6IGU572R5pyA5paw5Yqo5oCB');
$cfg_Cs[10]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[11]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[12]=array(11,1,1,'5ZCI5L2c5Yqo5oCB');
$cfg_Cs[13]=array(11,1,1,'5oqA5pyv5Lit5b+D');
$cfg_Cs[14]=array(11,1,1,'6KGM5Lia5L+h5oGv');
$cfg_Cs[16]=array(0,1,1,'5oiR55qE5Zui6Zif');
?>