<div class="rowFluid"> 
					                  <a href="[field:arcurl/]">
					                  <div class="kzf-mod-new-li">
					                    <div class="span2">
					                      <div class="kzf-mod-new-time-box">
					                        <div class="kzf-mod-new-time-date"><span>[field:pubdate function="MyDate('m',@me)" /]</span>/<span>[field:pubdate function="MyDate('d',@me)" /]</span></div>
					                        <div class="kzf-mod-new-time-year">[field:pubdate function="MyDate('Y',@me)" /]</div>
					                      </div>
					                    </div>
					                    <div class="span10">
					                      <div class="kzf-mod-new-box">
					                        <div class="kzf-mod-new-title">[field:title/]</div>
					                        <div class="kzf-mod-new-text"> [field:description/]</div>
					                      </div>
					                    </div>
					                  </div>
					                  </a> 
					                </div>