<div class="right-bottom">
								<a href="[field:arcurl/]" target="_blank">
									<p style="width: 280px; height: 148px; z-index: 4;"><img class="wqd-img" ondragstart="return false;" src="[field:picname/]" alt="缩略图"></p>
									<p class="wqd-text-article3">
										<span style="color:#696969;">
											<span style="font-size:12px;">[field:title/]</span>
										</span>
									</p>
								</a>
							</div>