<div class="rowFluid"> 
                  <a href="[field:arcurl/]">
                  <div class="kzf-mod-new-li">
                    <div class="span2">
                      <div class="kzf-mod-new-time-box">
                        <div class="kzf-mod-new-time-date"><span>[field:pubdate function="MyDate('m',@me)" /]</span>/<span>[field:pubdate function="MyDate('d',@me)" /]</span></div>
                        <div class="kzf-mod-new-time-year">[field:pubdate function="MyDate('Y',@me)" /]</div>
                      </div>
                    </div>
                    <div class="span10">
                      <div class="kzf-mod-new-box">
                        <div class="kzf-mod-new-title">[field:title/]</div>
                        <div class="kzf-mod-new-text"> 价格更低：网站建设公司自行开发系统，一般的开发成本都会在千元以上，就算网站建设公司使用自己已经开发的系统建站，客户的一些个性化需要也需要二次开发，而使用企业网站管...</div>
                      </div>
                    </div>
                  </div>
                  </a> 
                </div>