<div class="customer">
								<img class="wqd-img" ondragstart="return false;" src="[field:picname/]" alt="缩略图">
								<p class="wqd-text-article2 customer-top" style="text-align: center;"><span style="color:#D3D3D3;">[field:title /]</span></p>
								<p class="wqd-text-article3 customer-top" style="text-align: center;">
									<span style="font-size:12px;">
										<span style="color:#FFFFFF;">[field:description/]</span>
									</span>
								</p>
								<div class="wqdelementEdit customer-bottom" id="elementid14533030339880" style="width: 170px; height: 46px;  z-index: 9;" data-elementtype="button" wqdheight="48" wqdbgcolor="#03aaf5" data-elemandgroup="true" elementid="elementid14533030339880" data-zindex="9" wqdhref="0" wqdborderradius="9" wqdcolor="rgb(255, 255, 255)" wqdbordercolor="rgb(255, 255, 255)" wqdon="true" hoverbaccol="#a627b0">
									<div class="wqdelementEditBox">
										<a href="[field:arcurl/]" target="_blank" class="wqd-button wqdComponentBtn1 on" style="border-radius: 9px;" ondragstart="return false;" wqdbtnborder="false"><em>了解详情</em></a>
									</div> 
								</div>
							</div>