<div class="rowFluid" [field:global name="autoindex" runphp="yes"]if(@me%3==0)@me='class="mrnone"'; else @me="";[/field:global]> 
          <a href="[field:arcurl/]">
          <div class="kzf-mod-new-li">
            <div class="span2">
              <div class="kzf-mod-new-time-box">
                <div class="kzf-mod-new-time-date"><span>10</span>/<span>25</span></div>
                <div class="kzf-mod-new-time-year">2017</div>
              </div>
            </div>
            <div class="span10">
              <div class="kzf-mod-new-box">
                <div class="kzf-mod-new-title">[field:title/]</div>
                <div class="kzf-mod-new-text">[field:description/]</div>
              </div>
            </div>
          </div>
          </a> 
        </div>