<div class=" elementsContainer project-left" id="groupId1453362341857" style="left: 0px; top: 155px; width: 382px; height: 410px; z-index: 3;" data-maxzindex="0" data-elemandgroup="true" data-zindex="3" data-groupstatus="off" groupid="groupId1453362341857">
							<div class="wqdelementEditBox">
								<div class="wqdelementEdit" id="elementid14533623418570" style="width: 353px; height: 55px; left: 14.5px; top: 318px; z-index: 3;" data-elementtype="text" data-elemandgroup="true" elementid="elementid14533623418570" data-zindex="3">
									<div class="wqdelementEditBox" style="visibility: visible;" data-emptytexttemplate="article3">
										<p class="wqd-text-article3" style="text-align: center;">
											<span style="color:#696969;">
												<span style="font-size:12px;">[field:description/]</span>
											</span>
										</p>
									</div>

								</div>

								<div class="wqdelementEdit" id="elementid14533623418571" style="width: 382px; height: 410px; left: 0px; top: 0px; z-index: 2;" data-elementtype="button" wqdheight="45" wqdbgcolor="rgba(255,255,255,0)" data-elemandgroup="true" elementid="elementid14533623418571" data-zindex="2" wqdhref="0" wqdborderradius="5" wqdcolor="rgb(117, 197, 93)" wqdbordercolor="#b1b1b1" wqdon="false" wqdborder_width="2">
									<div class="wqdelementEditBox">
										<a class="wqd-button wqdComponentBtn2" style="border-width: 1px; border-style: solid;" ondragstart="return false;" wqdbtnborder="false"><em></em>
										</a>
									</div> 
								</div>

								<div class="wqdelementEdit" id="elementid14533623418572" style="width: 364px; height: 231px; left: 9px; top: 10px; z-index: 4;" data-elementtype="img" data-elemandgroup="true" elementid="elementid14533623418572" data-zindex="4">
									<div class="wqdelementEditBox">
										<img class="wqd-img" ondragstart="return false;" src="[field:picname/]">
									</div>
								</div>


								<div class="wqdelementEdit" id="elementid14533623418573" style="width: 189px; height: 28px; left: 103.5px; top: 283px; z-index: 5;" data-elementtype="text" data-elemandgroup="true" elementid="elementid14533623418573" data-zindex="5">
									<div class="wqdelementEditBox" style="visibility: visible;" data-emptytexttemplate="article2">
										<p class="wqd-text-article2" style="text-align: center;">
											<span style="color:#03aaf5;">[field:title/]</span>
										</p>
									</div>
								</div>

							</div>
						</div>