<div class="indexteam">
								<div class="wqdelementEdit" id="elementid14533016454830" style="width: 292px; height: 281px;  z-index: 3;" data-elementtype="img" data-elemandgroup="true" elementid="elementid14533016454830" data-zindex="3">
									<div class="wqdelementEditBox">
										<img class="wqd-img" ondragstart="return false;" src="[field:picname/]">
									</div>
								</div>
							</div>