<div class="wqdelementEdit" id="elementId1476929701592" style="width: 263px; height: 31px; left: 42.5px; top: 194px; z-index: 5;" data-elementtype="text" data-elemandgroup="true" elementid="elementId1476929701592" data-zindex="5">
									<div class="wqdelementEditBox" style="visibility: visible;" data-emptytexttemplate="article1">
										<p class="wqd-text-article1" style="text-align: center;"><span style="color:#03aaf5;">[field:title /]</span></p>
									</div>
								</div>

								<div class="wqdelementEdit" id="elementId1476929701601" style="width: 367px; height: 76px; left: 0px; top: 237px; z-index: 9;" data-elementtype="text" data-elemandgroup="true" elementid="elementId1476929701601" data-zindex="9">
									<div class="wqdelementEditBox" style="visibility: visible;" data-emptytexttemplate="article1">
										<p class="wqd-text-article3" style="text-align: center;">
											<span style="font-size:12px;">
												<span style="color:#696969;">[field:description/]</span>
											</span>
										</p>
										<p class="wqd-text-article1" style="text-align: center;"><br></p>
　									</div>
								</div>
								<div class="wqdelementEdit" id="elementId1476929701603" style="width: 125px; height: 30px; left: 111.5px; top: 313px; z-index: 11;" data-elementtype="line" data-elemandgroup="true" elementid="elementId1476929701603" data-zindex="11" wqdhref="0" wqdpathfill="#03aaf5">
									<div class="wqdelementEditBox">
										<div class="wqd-line" style="height:0;border-top:1px solid #3d9be9;position:relative;top:50%;"></div>
									</div> 
								</div>