<div class="about_news">
							
							<p class="wqd-text-article2" style="text-align: center;">
								<strong><span style="color:#03aaf5;">[field:title /]/span></strong>
							</p>
							<p class="wqd-text-article1" style="text-align: center;">　</p>
							
							<p class="wqd-text-article3" style="text-align: center;">
								<span style="font-size:12px;">
									<span style="color:#696969;">[field:description/]</span>
								</span>
							</p>

							<div class="wqdelementEdit news_bottom" id="elementid14533077091550" style="width: 170px; height: 46px;   z-index: 8;" data-elementtype="button" wqdheight="48" wqdbgcolor="#03aaf5" data-elemandgroup="true" elementid="elementid14533077091550" data-zindex="8" wqdhref="0" wqdborderradius="9" wqdcolor="rgb(255, 255, 255)" wqdbordercolor="rgb(255, 255, 255)" wqdon="true" hoverbaccol="#a627b0">
								<div class="wqdelementEditBox">
									<a class="wqd-button wqdComponentBtn1 on" style="border-radius: 9px; " ondragstart="return false;" wqdbtnborder="false"><em>了解详情</em>
									</a>
								</div> 
							</div>
						</div>