
							<div class="wqdelementEdit" id="elementId1453303911863" style="width: 140px; height: 117px; left: 13px; top: 152.5px; z-index: 2;" data-elementtype="img" data-elemandgroup="true" elementid="elementId1453303911863" data-zindex="2">
								<div class="wqdelementEditBox">
									[field:logo /]
									<img class="wqd-img" ondragstart="return false;" src="{dede:global.cfg_templets_skin/}/images/yq0KZFafpuqAdmdaAAAM5TZhxXw233.png">
								</div>
							</div>
							