<div class="left-news">
								<div class="left-top">
									<p class="wqd-text-article1">
										<span style="color:#000000;">
											<span style="font-size:40px;">[field:title/]</span>
										</span>
									</p>
								</div>
								<span>时间：[field:pubdate function="GetDateTimeMK(@me)" /]</span>
								<div class="left-bottom">
									<img class="wqd-img" ondragstart="return false;" src="[field:picname/]">
								</div>
								<p class="wqd-text-article3">
									<span style="color:#696969;">
										<span style="font-size:12px;">[field:description/]</span>
									</span>
								</p>
								<a href="[field:arcurl/]" target="_blank" class="wqd-button wqdComponentBtn1 on left-bottom" style="left: 0px;  width: 170px; height: 46px; z-index: 17; border-radius: 9px;" ><em>了解详情</em></a>
								<div class="wqd-line left-xian" style="height:0;border-top:1px solid #b5b5b5;position:relative;top:50%;">
								</div>
							</div>